### ISSUE TITLE
Error 500 when Rabbit working with path_prefix="/rabbitmq"

### ISSUE THREAD

**Issue by wildloop** [rabbitmq/rabbitmq-shovel#37] opened 2017-12-10 22:46 UTC
Error stacktrace: 

```
body 500 Error put #/shovel-parameters Cannot read property 'substr' of undefined TypeError: 500 Error put #/shovel-parameters Cannot read property 'substr' of undefined
    at context_prototype.<anonymous> (shovel.js:20)
    at nextRoute (sammy-0.7.6.min.js:5)
    at wrapped_route (sammy-0.7.6.min.js:5)
    at Sammy.Application.runRoute (sammy-0.7.6.min.js:5)
    at Sammy.Application._checkFormSubmission (sammy-0.7.6.min.js:5)
    at context_prototype.<anonymous> (sammy-0.7.6.min.js:5)
    at HTMLBodyElement.listener_callback (sammy-0.7.6.min.js:5)
    at HTMLBodyElement.dispatch (jquery-1.12.4.min.js:3)
    at HTMLBodyElement.r.handle (jquery-1.12.4.min.js:3)
```

Rabbitmq v.3.7.0, Erlang v20.1.
Config:

```
[
  {rabbitmq_management, 
    [{path_prefix, "/rabbitmq"}]}
].
```

**Comment by michaelklishin** [comment] 2017-12-11 07:19
This looks like a duplicate of https://github.com/rabbitmq/rabbitmq-web-dispatch/issues/31.

**Closed by michaelklishin** 2017-12-11 07:19 UTC

**Comment by eks5115** [comment] 2019-03-01 03:02
I have the same problem in version 3.7.0. But I can only use this version. How to do? @michaelklishin

**Comment by michaelklishin** [comment] 2019-03-01 10:10
`3.7.0` is [12 patch releases behind](https://www.rabbitmq.com/changelog.html). Please upgrade, there is no other option.
